site_name: My Docs
site_url: http://badele.github.io/mydocs/
site_description: My Documentations
site_author: Bruno Adele

repo_url: https://github.com/badele/mydocs/

theme: yeti


pages:
  - Main: index.md
  - System: system/index.md
  - Development: development/index.md

markdown_extensions:
    - toc:
        permalink: _
    - admonition:

copyright: 'Documentations in Creative Commons. Twitter: <a href="https://twitter.com/jesuislibre">Bruno Adele</a> / Website: <a href="http://bruno.adele.im/">bruno.adele.im</a>.'
